/**
 * App configuration: questions, widgets, pillars, defaults.
 */
const MoodAppConfig = (function () {
  const REQUIRED_QUESTIONS = [
    {
      id: 'mood',
      category: 'state',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Настроение',
      question: 'Какое у тебя сейчас настроение?',
      pillar: 'state',
      color: '#7FA7F2',
      scaleLabels: { 1: 'низко', 3: 'нормально', 5: 'отлично' },
    },
    {
      id: 'stress',
      category: 'stress_anxiety',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Стресс',
      question: 'Какой уровень стресса сейчас?',
      pillar: 'stress',
      color: '#CDBBFF',
      scaleLabels: { 1: 'спокойно', 3: 'умеренно', 5: 'сильно' },
    },
    {
      id: 'anxiety',
      category: 'stress_anxiety',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Тревога',
      question: 'Насколько тревожно сейчас?',
      pillar: 'stress',
      color: '#CDBBFF',
      scaleLabels: { 1: 'спокойно', 3: 'умеренно', 5: 'сильно' },
    },
    {
      id: 'energy',
      category: 'state',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Энергия',
      question: 'Сколько у тебя сейчас энергии?',
      pillar: 'state',
      color: '#FFE26A',
      scaleLabels: { 1: 'мало', 3: 'нормально', 5: 'много' },
    },
  ];

  const OPTIONAL_WIDGETS = [
    {
      id: 'sleep_hours',
      category: 'sleep',
      type: 'number',
      label: 'Часы сна',
      title: 'Сон',
      description: 'Отслеживай часы и качество сна',
      question: 'Сколько часов ты спал?',
      pillar: 'sleep',
      color: '#9EDB73',
      icon: '🌙',
      numberMin: 0,
      numberMax: 24,
      numberStep: 0.5,
    },
    {
      id: 'sleep_quality',
      category: 'sleep',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Качество сна',
      title: 'Качество сна',
      description: 'Как прошла ночь',
      question: 'Как прошла ночь?',
      pillar: 'sleep',
      color: '#9EDB73',
      icon: '✨',
      scaleLabels: { 1: 'плохо', 3: 'нормально', 5: 'отлично' },
    },
    {
      id: 'wake_up_quality',
      category: 'sleep',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Пробуждение',
      title: 'Пробуждение',
      description: 'Как ты проснулся утром',
      question: 'Как ты проснулся?',
      pillar: 'sleep',
      color: '#9EDB73',
      icon: '☀️',
      scaleLabels: { 1: 'тяжело', 3: 'нормально', 5: 'бодро' },
    },
    {
      id: 'physical_activity',
      category: 'activity',
      type: 'scale',
      scaleMin: 0,
      scaleMax: 3,
      label: 'Активность',
      title: 'Физическая активность',
      description: 'Лёгкая, средняя или интенсивная',
      question: 'Была ли физическая активность сегодня?',
      pillar: 'activity',
      color: '#F5822A',
      icon: '🏃',
      scaleOptions: [
        { value: 0, label: 'не было' },
        { value: 1, label: 'лёгкая' },
        { value: 2, label: 'средняя' },
        { value: 3, label: 'интенсивная' },
      ],
    },
    {
      id: 'body_state',
      category: 'activity',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Тело',
      title: 'Состояние тела',
      description: 'Как чувствует себя тело',
      question: 'Как сейчас чувствует себя тело?',
      pillar: 'activity',
      color: '#F5822A',
      icon: '💪',
      scaleLabels: { 1: 'плохо', 3: 'нормально', 5: 'хорошо' },
    },
    {
      id: 'body_tension',
      category: 'activity',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Напряжение',
      title: 'Напряжение в теле',
      description: 'Есть ли зажимы и напряжение',
      question: 'Есть ли напряжение в теле?',
      pillar: 'activity',
      color: '#F5822A',
      icon: '🫧',
      scaleLabels: { 1: 'нет', 3: 'немного', 5: 'сильно' },
    },
    {
      id: 'negative_event',
      category: 'stress_anxiety',
      type: 'scale',
      scaleMin: 0,
      scaleMax: 2,
      label: 'Событие',
      title: 'Негативное событие',
      description: 'Что ухудшило состояние',
      question: 'Было ли что-то, что ухудшило состояние?',
      pillar: 'stress',
      color: '#CDBBFF',
      icon: '☁️',
      scaleOptions: [
        { value: 0, label: 'нет' },
        { value: 1, label: 'немного' },
        { value: 2, label: 'сильно' },
      ],
    },
    {
      id: 'factors',
      category: 'stress_anxiety',
      type: 'tags',
      label: 'Факторы',
      title: 'Факторы влияния',
      description: 'Что могло повлиять на состояние',
      question: 'Что могло повлиять на состояние?',
      pillar: 'stress',
      color: '#CDBBFF',
      icon: '🏷️',
      tags: [
        'сон',
        'работа',
        'отношения',
        'семья',
        'деньги',
        'здоровье',
        'соцсети',
        'одиночество',
        'конфликт',
        'другое',
      ],
    },
    {
      id: 'nutrition',
      category: 'activity',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 5,
      label: 'Питание',
      title: 'Питание',
      description: 'Как ты питался сегодня',
      question: 'Как ты сегодня питался?',
      pillar: 'activity',
      color: '#FFE26A',
      icon: '🥗',
      scaleLabels: { 1: 'плохо', 3: 'нормально', 5: 'хорошо' },
    },
    {
      id: 'note',
      category: 'state',
      type: 'textarea',
      label: 'Заметка',
      title: 'Заметка',
      description: 'Добавляй контекст к своему дню',
      question: 'Хочешь добавить короткую заметку?',
      pillar: 'state',
      color: '#7FA7F2',
      icon: '📝',
    },
  ];

  const PILLARS = [
    {
      id: 'state',
      title: 'Состояние',
      color: '#7FA7F2',
      bg: 'rgba(127, 167, 242, 0.15)',
      fields: ['mood', 'energy'],
      icon: '💙',
    },
    {
      id: 'stress',
      title: 'Стресс / тревога',
      color: '#CDBBFF',
      bg: 'rgba(205, 187, 255, 0.2)',
      fields: ['stress', 'anxiety'],
      icon: '🌸',
    },
    {
      id: 'sleep',
      title: 'Сон',
      color: '#9EDB73',
      bg: 'rgba(158, 219, 115, 0.15)',
      fields: ['sleep_hours', 'sleep_quality', 'wake_up_quality'],
      icon: '🌙',
    },
    {
      id: 'activity',
      title: 'Активность',
      color: '#F5822A',
      bg: 'rgba(245, 130, 42, 0.12)',
      fields: ['physical_activity', 'body_state', 'nutrition'],
      icon: '✨',
    },
  ];

  const TRACKING_GOALS = [
    { id: 'mood', label: 'состояние' },
    { id: 'stress', label: 'стресс' },
    { id: 'anxiety', label: 'тревогу' },
    { id: 'sleep', label: 'сон' },
    { id: 'activity', label: 'физическую активность' },
    { id: 'energy', label: 'энергию' },
    { id: 'notes', label: 'заметки' },
  ];

  const DEFAULT_ENABLED_WIDGETS = {
    sleep_hours: true,
    sleep_quality: true,
    wake_up_quality: false,
    physical_activity: true,
    body_state: false,
    body_tension: false,
    negative_event: true,
    factors: true,
    nutrition: false,
    note: true,
  };

  const STORAGE_KEYS = {
    userProfile: 'moodApp_userProfile',
    enabledWidgets: 'moodApp_enabledWidgets',
    entries: 'moodApp_entries',
  };

  function getQuestionById(id) {
    const required = REQUIRED_QUESTIONS.find((q) => q.id === id);
    if (required) return required;
    return OPTIONAL_WIDGETS.find((w) => w.id === id) || null;
  }

  function getAllQuestionsForCheckin(enabledWidgets) {
    const optional = OPTIONAL_WIDGETS.filter((w) => enabledWidgets[w.id]);
    return [...REQUIRED_QUESTIONS, ...optional];
  }

  return {
    REQUIRED_QUESTIONS,
    OPTIONAL_WIDGETS,
    PILLARS,
    TRACKING_GOALS,
    DEFAULT_ENABLED_WIDGETS,
    STORAGE_KEYS,
    getQuestionById,
    getAllQuestionsForCheckin,
  };
})();
